version: '3.3'

services:
  web:
    build: .
    volumes:
      - .:/usr/src/app

  worker:
    build: .
    volumes:
      - .:/usr/src/app

  capture_events:
    build: .
    volumes:
      - .:/usr/src/app

  builder:
    image: node:8
    volumes:
      - ./castor/web/static/web:/usr/src/app
    working_dir: /usr/src/app
    command: npm install
