# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-22 17:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('docker_servers', '0002_auto_20170122_1726'),
    ]

    operations = [
        migrations.CreateModel(
            name='DockerEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capture_time', models.DateTimeField(auto_now=True)),
                ('data', models.CharField(max_length=65535)),
                ('docker_server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docker_servers.DockerServer')),
            ],
        ),
    ]
