# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-29 15:08
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('docker_events', '0001_initial'), ('docker_events', '0002_auto_20170123_0930'), ('docker_events', '0003_auto_20170129_1118')]

    initial = True

    dependencies = [
        ('docker_servers', '0002_auto_20170122_1726'),
    ]

    operations = [
        migrations.CreateModel(
            name='DockerEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capture_time', models.DateTimeField(auto_now=True)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(default={}, unique=True)),
                ('docker_server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docker_servers.DockerServer')),
            ],
        ),
    ]
