# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-20 18:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docker_events', '0003_auto_20170129_1118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dockerevent',
            name='capture_time',
        ),
        migrations.RemoveField(
            model_name='dockerevent',
            name='data',
        ),
        migrations.RemoveField(
            model_name='dockerevent',
            name='docker_server',
        ),
    ]
