# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-22 18:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('docker_servers', '0003_auto_20170122_1730'),
        ('docker_events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dispatched_at', models.DateTimeField(auto_now=True)),
                ('delivery_duration', models.IntegerField()),
                ('request_headers', models.CharField(max_length=65535)),
                ('request_body', models.CharField(max_length=65535)),
                ('response_headers', models.CharField(max_length=65535)),
                ('response_body', models.CharField(max_length=65535)),
                ('docker_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docker_events.DockerEvent')),
            ],
        ),
        migrations.CreateModel(
            name='WebHook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payload_url', models.CharField(max_length=255)),
                ('docker_server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docker_servers.DockerServer')),
            ],
        ),
        migrations.AddField(
            model_name='notification',
            name='webhook',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webhooks.WebHook'),
        ),
    ]
