# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-23 08:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0002_webhook_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='delivered',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='failure_reason',
            field=models.CharField(blank=True, default='', max_length=65535),
        ),
    ]
