# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-23 08:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0003_auto_20170123_0824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='request_body',
            field=models.CharField(max_length=65535, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='request_headers',
            field=models.CharField(max_length=65535, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='response_body',
            field=models.CharField(max_length=65535, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='response_headers',
            field=models.CharField(max_length=65535, null=True),
        ),
    ]
