# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-23 09:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0005_auto_20170123_0930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='failure_reason',
            field=models.TextField(blank=True, max_length=65535, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='request_body',
            field=models.TextField(blank=True, max_length=65535, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='response_body',
            field=models.TextField(blank=True, max_length=65535, null=True),
        ),
    ]
