# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-23 10:25
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0006_auto_20170123_0933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='request_headers',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='response_headers',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}, null=True),
        ),
    ]
