# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-23 15:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0007_auto_20170123_1025'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='status_code',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
