# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-24 00:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0008_notification_status_code'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Notification',
            new_name='Delivery',
        ),
    ]
