# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-29 13:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0009_auto_20170124_0057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='failure_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='request_body',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='response_body',
            field=models.TextField(blank=True, null=True),
        ),
    ]
