# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-20 17:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0010_auto_20170129_1356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='docker_event',
        ),
    ]
