# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-11-09 10:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0011_remove_delivery_docker_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='webhook',
        ),
        migrations.DeleteModel(
            name='Delivery',
        ),
    ]
