# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-22 17:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docker_servers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dockerserver',
            name='docker_cert_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
