# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-22 17:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docker_servers', '0002_auto_20170122_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dockerserver',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
