name: Build

permissions:
  packages: write

on:
  workflow_call:
    inputs:
      image:
        required: true
        description: The Docker image tag to use for building
        type: string


env:
  DOCKER_IMAGE: ${{ inputs.image }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v2
      - uses: docker/login-action@v2.1.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/bake-action@v2
        with:
          push: true
